### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by lingling-fan** [caarmen/nounours-android#19]
//package name: ca.rmen.nounours
//version: 3.4.3
 java.lang.NullPointerException
 	at ca.rmen.nounours.android.handheld.compat.EnvironmentCompat.getExternalFilesDir(EnvironmentCompat.java:48)
 	at ca.rmen.nounours.android.handheld.util.AnimationUtil.saveAnimation(AnimationUtil.java:93)
 	at ca.rmen.nounours.android.handheld.AnimationSaveService.handleActionSaveAnimation(AnimationSaveService.java:100)
 	at ca.rmen.nounours.android.handheld.AnimationSaveService.onHandleIntent(AnimationSaveService.java:80)
 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
 	at android.os.Handler.dispatchMessage(Handler.java:99)
 	at android.os.Looper.loop(Looper.java:137)
 	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by caarmen** [comment]
Thanks for the reports.

Please provide steps to reproduce the crashes, or provide some description to give some context.

Please note that the play store console already contains crash reports, and provides more info (like the types of devices and versions of Android impacted). If these issues on github don't provide more info then I may have to close them as the play store console reports are sufficient.

Did a bot report these crashes?
